import { describe, it, expect } from 'vitest';
import { generateTypeScript, generateEnvExample } from '../../src/core/generator';
import type { EnvSchema } from '../../src/types';

describe('generator', () => {
  describe('generateTypeScript', () => {
    it('should generate TypeScript for string variable', () => {
      const schema: EnvSchema = {
        variables: {
          API_KEY: {
            type: 'string',
            required: true,
            description: 'API key for auth',
          },
        },
      };

      const output = generateTypeScript(schema);

      expect(output).toContain('API_KEY: string');
      expect(output).toContain('/** API key for auth */');
    });

    it('should generate TypeScript for number variable', () => {
      const schema: EnvSchema = {
        variables: {
          PORT: {
            type: 'number',
            required: true,
          },
        },
      };

      const output = generateTypeScript(schema);

      expect(output).toContain('PORT: number');
    });

    it('should generate TypeScript for boolean variable', () => {
      const schema: EnvSchema = {
        variables: {
          DEBUG: {
            type: 'boolean',
            required: true,
          },
        },
      };

      const output = generateTypeScript(schema);

      expect(output).toContain('DEBUG: boolean');
    });

    it('should generate literal union for enum', () => {
      const schema: EnvSchema = {
        variables: {
          NODE_ENV: {
            type: 'string',
            required: true,
            enum: ['development', 'production', 'test'],
          },
        },
      };

      const output = generateTypeScript(schema);

      expect(output).toContain("'development' | 'production' | 'test'");
    });

    it('should mark optional variables with ?', () => {
      const schema: EnvSchema = {
        variables: {
          OPTIONAL_VAR: {
            type: 'string',
            required: false,
          },
        },
      };

      const output = generateTypeScript(schema);

      expect(output).toContain('OPTIONAL_VAR?:');
    });

    it('should generate ProcessEnv namespace augmentation', () => {
      const schema: EnvSchema = {
        variables: {
          MY_VAR: {
            type: 'string',
            required: true,
          },
        },
      };

      const output = generateTypeScript(schema, { namespace: true });

      expect(output).toContain('declare global');
      expect(output).toContain('namespace NodeJS');
      expect(output).toContain('interface ProcessEnv');
    });

    it('should skip namespace when disabled', () => {
      const schema: EnvSchema = {
        variables: {
          MY_VAR: {
            type: 'string',
            required: true,
          },
        },
      };

      const output = generateTypeScript(schema, { namespace: false });

      expect(output).not.toContain('declare global');
      expect(output).not.toContain('namespace NodeJS');
    });

    it('should generate RequiredEnvVars type', () => {
      const schema: EnvSchema = {
        variables: {
          REQUIRED_1: { type: 'string', required: true },
          REQUIRED_2: { type: 'string', required: true },
          OPTIONAL: { type: 'string', required: false },
        },
      };

      const output = generateTypeScript(schema);

      expect(output).toContain('RequiredEnvVars');
      expect(output).toContain("'REQUIRED_1'");
      expect(output).toContain("'REQUIRED_2'");
    });

    it('should generate OptionalEnvVars type', () => {
      const schema: EnvSchema = {
        variables: {
          REQUIRED: { type: 'string', required: true },
          OPTIONAL: { type: 'string', required: false },
        },
      };

      const output = generateTypeScript(schema);

      expect(output).toContain('OptionalEnvVars');
      expect(output).toContain("'OPTIONAL'");
    });

    it('should include auto-generated header', () => {
      const schema: EnvSchema = { variables: {} };
      const output = generateTypeScript(schema);

      expect(output).toContain('Auto-generated by env-guardian');
      expect(output).toContain('Do not edit');
    });
  });

  describe('generateEnvExample', () => {
    it('should generate .env.example content', () => {
      const schema: EnvSchema = {
        variables: {
          DATABASE_URL: {
            type: 'string',
            required: true,
            description: 'Database connection string',
          },
        },
      };

      const output = generateEnvExample(schema);

      expect(output).toContain('DATABASE_URL=');
      expect(output).toContain('# Database connection string');
    });

    it('should include default values', () => {
      const schema: EnvSchema = {
        variables: {
          PORT: {
            type: 'number',
            required: false,
            default: 3000,
          },
        },
      };

      const output = generateEnvExample(schema);

      expect(output).toContain('PORT=3000');
    });

    it('should include enum options in comments', () => {
      const schema: EnvSchema = {
        variables: {
          NODE_ENV: {
            type: 'string',
            required: true,
            enum: ['development', 'production', 'test'],
          },
        },
      };

      const output = generateEnvExample(schema);

      expect(output).toContain('# Allowed values: development, production, test');
    });

    it('should mark optional variables', () => {
      const schema: EnvSchema = {
        variables: {
          OPTIONAL_VAR: {
            type: 'string',
            required: false,
          },
        },
      };

      const output = generateEnvExample(schema);

      expect(output).toContain('# Optional');
    });

    it('should skip comments when disabled', () => {
      const schema: EnvSchema = {
        variables: {
          MY_VAR: {
            type: 'string',
            required: true,
            description: 'Some description',
          },
        },
      };

      const output = generateEnvExample(schema, { comments: false });

      expect(output).not.toContain('#');
      expect(output).toContain('MY_VAR=');
    });

    it('should include header comment', () => {
      const schema: EnvSchema = { variables: {} };
      const output = generateEnvExample(schema);

      expect(output).toContain('# Environment variables');
      expect(output).toContain('# Generated by env-guardian');
    });
  });
});
